# Generated by ChatGPT on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortalityevent",
            name="poultry_type",
            field=models.CharField(
                choices=[("white", "Pui albi"), ("colored", "Pui colorați")],
                default="white",
                max_length=10,
            ),
        ),
    ]
