# Generated by Django 5.2.9 on 2025-12-28 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT')], max_length=10)),
                ('path', models.CharField(blank=True, default='', max_length=300)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='auditlog_au_created_778b93_idx',
            old_name='auditlog_a_created_9c9b6f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='auditlog_au_actor_i_c7aafa_idx',
            old_name='auditlog_a_actor_c_f51b7f_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='auditlog_au_model_b9a914_idx',
            old_name='auditlog_a_model_c_8b5c52_idx',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['created_at'], name='auditlog_ac_created_d453bc_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['actor', 'created_at'], name='auditlog_ac_actor_i_ee8a25_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['event', 'created_at'], name='auditlog_ac_event_66dc85_idx'),
        ),
    ]
