# Generated by ChatGPT on 2026-01-06

from django.db import migrations, models


def forwards_copy_initial_to_white(apps, schema_editor):
    """Pentru datele vechi: dacă nu există defalcare, considerăm totul ca 'pui albi'."""
    Flock = apps.get_model("core", "Flock")
    for f in Flock.objects.all():
        try:
            w = int(getattr(f, "initial_white_count", 0) or 0)
            c = int(getattr(f, "initial_colored_count", 0) or 0)
        except Exception:
            w, c = 0, 0

        if (w == 0 and c == 0) and int(getattr(f, "initial_count", 0) or 0) > 0:
            f.initial_white_count = int(getattr(f, "initial_count", 0) or 0)
            f.initial_colored_count = 0
            f.save(update_fields=["initial_white_count", "initial_colored_count"])


def backwards_noop(apps, schema_editor):
    # Nu ștergem date (noop)
    return


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flock",
            name="initial_white_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flock",
            name="initial_colored_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(forwards_copy_initial_to_white, backwards_noop),
    ]
